### ISSUE TITLE
AppGroups

### ISSUE THREAD

**Issue by shevtsod** [matryoshkadoll/matryoshka-server#3]
Requirements related to `AppGroups` model and how it ties certain applications to certain users.

**Comment by shevtsod** [comment]
> Should users be able to assign themselves to groups?

Yes, but the admin must approve.

**Comment by shevtsod** [comment]
> Can a user belong to multiple groups?

Yes. User roles will be based on their groups

**Comment by shevtsod** [comment]
> Can an application belong to multiple groups?\

Yes.

**Comment by oscar666666** [comment]
I think the administrator is the only one need to register for an account (for the entire organization). All other user accounts should be generated by the administrator. Admin is(are) the only one can upload app.

otherwise everyone can assign them to an organization and have access to all the software belong to the org. (some unique software may only for that organization)

**Comment by shevtsod** [comment]
Discuss user permission conflicts.
