### ISSUE TITLE
Create API sub-domain

### ISSUE THREAD

**Issue by oscar666666** [matryoshkadoll/matryoshka-server#8]
a sub domain for api would be a good idea to seperate admin page and restful api.

**Comment by shevtsod** [comment]
This issue should already be implemented in the API routes file:

https://github.com/ense-400-capstone-appstore/capstone-appstore-server/blob/master/routes/api.php

Rather than your suggestion of using a subdomain (e.g., `api.appstore.com`) the API routes live under `/api/v1/` (e.g., `appstore.com/api/v1/`) which I believe is somewhat of a standard for API routes.

We could definitely move these routes into a subdomain and [Laravel supports this](https://laravel.com/docs/5.7/routing#route-group-sub-domain-routing) but I think that this would be somewhat less flexible as the routes would then depend on our domain name.

**Comment by oscar666666** [comment]
ok
